-- =====================================================
-- ALTERAÇÃO: Permitir valor 'A' (Apoio) na coluna TIPO_FUNCIONARIO
-- Tabela: FOCCO3I.TGAZIN_FAIXA_COMISSAO
-- Data: 29/04/2026
-- =====================================================

-- Verificar constraints existentes na tabela
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM ALL_CONSTRAINTS
WHERE OWNER = 'FOCCO3I'
AND TABLE_NAME = 'TGAZIN_FAIXA_COMISSAO';

-- Verificar constraints existentes na coluna TIPO_FUNCIONARIO
SELECT CC.CONSTRAINT_NAME, CC.COLUMN_NAME, C.SEARCH_CONDITION
FROM ALL_CONS_COLUMNS CC
JOIN ALL_CONSTRAINTS C ON C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME AND C.OWNER = CC.OWNER
WHERE CC.OWNER = 'FOCCO3I'
AND CC.TABLE_NAME = 'TGAZIN_FAIXA_COMISSAO'
AND CC.COLUMN_NAME = 'TIPO_FUNCIONARIO';

-- PASSO 1: Remover constraint antiga (ajuste o nome conforme resultado da query acima)
-- ALTER TABLE FOCCO3I.TGAZIN_FAIXA_COMISSAO DROP CONSTRAINT <NOME_DA_CONSTRAINT>;

-- PASSO 2: Recriar constraint com 'A' incluído
-- ALTER TABLE FOCCO3I.TGAZIN_FAIXA_COMISSAO ADD CONSTRAINT CHK_FAIXA_TIPO_FUNC
--     CHECK (TIPO_FUNCIONARIO IN ('N', 'T', 'A'));

-- OU: Caso a coluna não tenha constraint, apenas adicionar:
ALTER TABLE FOCCO3I.TGAZIN_FAIXA_COMISSAO ADD CONSTRAINT CHK_FAIXA_TIPO_FUNC
    CHECK (TIPO_FUNCIONARIO IN ('N', 'T', 'A'));

COMMIT;
