<?php
/**
 * Insere/atualiza o SQL "faturamento.programacao.listar" no GAZIN_SQLS.
 * Executar via: docker exec comissao_colchao php //var/www/html/exec2026-05-20-insert-sql-programacao-pedidos.php
 */

require_once __DIR__ . '/vendor/autoload.php';

$idsql = 'faturamento.programacao.listar';

$sql = <<<'ENDSQL'
SELECT
    q.*,
    CASE
        WHEN TO_DATE(q.DATA_FORMATADA, 'DD/MM/YYYY') <= LAST_DAY(SYSDATE)
        THEN TO_CHAR(TRUNC(SYSDATE, 'MM'), 'DD/MM/YYYY')
        WHEN TO_DATE(q.DATA_FORMATADA, 'DD/MM/YYYY') <= LAST_DAY(ADD_MONTHS(SYSDATE, 1))
        THEN TO_CHAR(TRUNC(ADD_MONTHS(SYSDATE, 1), 'MM'), 'DD/MM/YYYY')
        ELSE 'SEM AGENDA'
    END AS AGENDA
FROM (
    SELECT
           TAB_PEDIDOS_RESUMO.DATA,
           TAB_PEDIDOS_RESUMO.TIPO_OPER,
           TAB_PEDIDOS_RESUMO.EMPR_ID,
           TAB_PEDIDOS_RESUMO.EMPRESA,
           TAB_PEDIDOS_RESUMO.DIVISAO_VENDA,
           TAB_PEDIDOS_RESUMO.CLIENTE,
           TAB_PEDIDOS_RESUMO.LINHA_PRODUTO,
           TAB_PEDIDOS_RESUMO.COD_CLIENTE,
           TAB_PEDIDOS_RESUMO.TIPO_CLIENTE,
           TAB_PEDIDOS_RESUMO.CIDADE,
           TAB_PEDIDOS_RESUMO.UF,
           TAB_PEDIDOS_RESUMO.PAIS,
           TAB_PEDIDOS_RESUMO.COD_TAB_VEN,
           TAB_PEDIDOS_RESUMO.TAB_VENDA,
           TAB_PEDIDOS_RESUMO.SEGMENTO_MERCADO,
           TAB_PEDIDOS_RESUMO.COD_REP,
           TAB_PEDIDOS_RESUMO.REPRESENTANTE,
           TAB_PEDIDOS_RESUMO.TIPO_REPRESENTANTE,
           TAB_PEDIDOS_RESUMO.PDV_NRO_PEDIDO,
           TAB_PEDIDOS_RESUMO.PDV_POSICAO,
           TAB_PEDIDOS_RESUMO.SIT_PDV_FIN,
           TAB_PEDIDOS_RESUMO.SIT_PDV_COM,
           TAB_PEDIDOS_RESUMO.PDV_SITUACAO,
           TAB_PEDIDOS_RESUMO.COD_ITEM,
           TAB_PEDIDOS_RESUMO.ID_CONFIG,
           TAB_PEDIDOS_RESUMO.ITEM,
           TAB_PEDIDOS_RESUMO.MASCARA,
           TAB_PEDIDOS_RESUMO.DATA_CARGA,
           TAB_PEDIDOS_RESUMO.EM_CARGA,
           TAB_PEDIDOS_RESUMO.PDV_VALOR_LIQUIDO,
           TAB_PEDIDOS_RESUMO.PDV_QTDE_VEND_MENOS_CANC,
           TAB_PEDIDOS_RESUMO.PDV_DATA_ENTREGA,
           TAB_PEDIDOS_RESUMO.PDV_VALOR_PENDENTE,
           TAB_PEDIDOS_RESUMO.PDV_VLR_PEND_CIPI,
           TAB_PEDIDOS_RESUMO.PDV_QTDE_PENDENTE,
           TAB_PEDIDOS_RESUMO.PDV_DIAS_ATRASO,
           TAB_PEDIDOS_RESUMO.DT_ENTREGA_CLI,
           TAB_PEDIDOS_RESUMO.PDV_VALOR_LIQ_IPI,
           TAB_PEDIDOS_RESUMO.PDV_VALOR_PEND_LIBERADO,
           TAB_PEDIDOS_RESUMO.PDV_VALOR_PEND_BLOQUEADO,
           TAB_PEDIDOS_RESUMO.PDV_DIAS_ENTRADA,
           TAB_PEDIDOS_RESUMO.PDV_DATA_FATURAMENTO,
           TAB_PEDIDOS_RESUMO.STATUS_CARGA,
           TAB_PEDIDOS_RESUMO.PDV_CARGA,
           TAB_PEDIDOS_RESUMO.ATENDIDO,
           TAB_PEDIDOS_RESUMO.OBS,
           TAB_PEDIDOS_RESUMO.OBS_NFS,
           TAB_PEDIDOS_RESUMO.OBS_ETIQUETA,
           TAB_PEDIDOS_RESUMO.DT_EMIS,
           TAB_PEDIDOS_RESUMO.UEP,
           TAB_PEDIDOS_RESUMO.COD_TANQUE,
           TAB_PEDIDOS_RESUMO.DESC_TANQUE,
           CLIENTES_PROGRAMACAO_V3.PROGRAMACAO,
    CASE
        WHEN REGEXP_LIKE(TO_CHAR(TAB_PEDIDOS_RESUMO.DATA_CARGA),'(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{4}')
        THEN SUBSTR(TO_CHAR(TAB_PEDIDOS_RESUMO.DATA_CARGA),1,10)
        WHEN UPPER(TRIM(CLIENTES_PROGRAMACAO_V3.PROGRAMACAO)) = 'AGENDADO'
        THEN '31/12/' || TO_CHAR(SYSDATE,'YYYY')
        WHEN UPPER(TRIM(TAB_PEDIDOS_RESUMO.DIVISAO_VENDA)) IN ('VENDA RETIRA - INDUSTRIA','VENDA RETIRA - CARTAO DE CREDITO','VENDA DE RESIDUOS','VENDA DE PRODUTOS INDUSTRIA - ASSISTENCIA (NAO USAR NO TIGER)','VENDA REFATURAMENTO','ASSISTENCIA TECNICA (NAO USAR NO TIGER)','REMESSA POR CONTA E ORDEM DE TERCEIROS','VENDA POR CONTA E ORDEM DE TERCEIROS')
        THEN '31/12/' || TO_CHAR(SYSDATE,'YYYY')
        WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%IMED%' OR UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%URG%'
        THEN TO_CHAR(SYSDATE,'DD/MM/YYYY')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[13578]|1[02])/[0-9]{4}|(0[1-9]|[12][0-9]|30)/(0[469]|11)/[0-9]{4}|(0[1-9]|1[0-9]|2[0-8])/02/[0-9]{4}')
        THEN REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[13578]|1[02])/[0-9]{4}|(0[1-9]|[12][0-9]|30)/(0[469]|11)/[0-9]{4}|(0[1-9]|1[0-9]|2[0-8])/02/[0-9]{4}')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[13578]|1[02])/[0-9]{2}|(0[1-9]|[12][0-9]|30)/(0[469]|11)/[0-9]{2}|(0[1-9]|1[0-9]|2[0-8])/02/[0-9]{2}')
        THEN SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[13578]|1[02])/[0-9]{2}|(0[1-9]|[12][0-9]|30)/(0[469]|11)/[0-9]{2}|(0[1-9]|1[0-9]|2[0-8])/02/[0-9]{2}'),1,6)||'20'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[13578]|1[02])/[0-9]{2}|(0[1-9]|[12][0-9]|30)/(0[469]|11)/[0-9]{2}|(0[1-9]|1[0-9]|2[0-8])/02/[0-9]{2}'),7,2)
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])') AND NOT REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/[0-9]{2,4}')
        THEN REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])')||'/'||TO_CHAR(SYSDATE,'YYYY')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])') AND NOT REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{2,4}')
        THEN REPLACE(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])'),' -','/')||'/'||TO_CHAR(SYSDATE,'YYYY')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{4}')
        THEN REPLACE(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{4}'),'-','/')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.[0-9]{2}')
        THEN REPLACE(SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.[0-9]{2}'),1,5),'.','/')||'/20'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.[0-9]{2}'),7,2)
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{4}')
        THEN SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{4}'),1,2)||'/'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{4}'),3,2)||'/'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{4}'),5,4)
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'FINAL(\s+DE)?\s+(JANEIRO|FEVEREIRO|MARCO|MARCO|ABRIL|MAIO|JUNHO|JULHO|AGOSTO|SETEMBRO|OUTUBRO|NOVEMBRO|DEZEMBRO)')
        THEN CASE WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JANEIRO%' THEN '31/01/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%FEVEREIRO%' THEN '28/02/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MARCO%' OR UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MARCO%' THEN '31/03/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%ABRIL%' THEN '30/04/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MAIO%' THEN '31/05/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JUNHO%' THEN '30/06/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JULHO%' THEN '31/07/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%AGOSTO%' THEN '31/08/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%SETEMBRO%' THEN '30/09/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%OUTUBRO%' THEN '31/10/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%NOVEMBRO%' THEN '30/11/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%DEZEMBRO%' THEN '31/12/'||TO_CHAR(SYSDATE,'YYYY') END
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'INICIO(\s+DE)?\s+(JANEIRO|FEVEREIRO|MARCO|MARCO|ABRIL|MAIO|JUNHO|JULHO|AGOSTO|SETEMBRO|OUTUBRO|NOVEMBRO|DEZEMBRO)')
        THEN CASE WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JANEIRO%' THEN '01/01/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%FEVEREIRO%' THEN '01/02/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MARCO%' OR UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MARCO%' THEN '01/03/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%ABRIL%' THEN '01/04/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%MAIO%' THEN '01/05/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JUNHO%' THEN '01/06/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%JULHO%' THEN '01/07/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%AGOSTO%' THEN '01/08/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%SETEMBRO%' THEN '01/09/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%OUTUBRO%' THEN '01/10/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%NOVEMBRO%' THEN '01/11/'||TO_CHAR(SYSDATE,'YYYY') WHEN UPPER(TAB_PEDIDOS_RESUMO.OBS) LIKE '%DEZEMBRO%' THEN '01/12/'||TO_CHAR(SYSDATE,'YYYY') END
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+(0?[1-9]|1[0-2])')
        THEN CASE WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?1') THEN '31/01/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?2') THEN '28/02/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?3') THEN '31/03/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?4') THEN '30/04/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?5') THEN '31/05/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?6') THEN '30/06/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?7') THEN '31/07/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?8') THEN '31/08/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+0?9') THEN '30/09/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+10') THEN '31/10/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+11') THEN '30/11/'||TO_CHAR(SYSDATE,'YYYY') WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'MES\s+12') THEN '31/12/'||TO_CHAR(SYSDATE,'YYYY') END
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{2}(?![0-9])')
        THEN SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{2}(?![0-9])'),1,2)||'/'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{2}(?![0-9])'),3,2)||'/20'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])(0[1-9]|1[0-2])[0-9]{2}(?![0-9])'),5,2)
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.[0-9]{4}')
        THEN REPLACE(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.[0-9]{4}'),'.','/')
        WHEN REGEXP_LIKE(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{2}(?![0-9])')
        THEN SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{2}(?![0-9])'),1,5)||'/20'||SUBSTR(REGEXP_SUBSTR(TAB_PEDIDOS_RESUMO.OBS,'(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-[0-9]{2}(?![0-9])'),7,2)
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'PROXIMO\s+M.S|PR.XIMO\s+M.S')
        THEN CASE WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=1 THEN '01/01/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=2 THEN '01/02/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=3 THEN '01/03/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=4 THEN '01/04/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=5 THEN '01/05/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=6 THEN '01/06/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=7 THEN '01/07/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=8 THEN '01/08/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=9 THEN '01/09/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=10 THEN '01/10/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=11 THEN '01/11/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') WHEN TO_NUMBER(TO_CHAR(ADD_MONTHS(SYSDATE,1),'MM'))=12 THEN '01/12/'||TO_CHAR(ADD_MONTHS(SYSDATE,1),'YYYY') END
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'ULTIMO\s+DIA|.LTIMO\s+DIA')
        THEN CASE WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=1 THEN '31/01/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=2 THEN '28/02/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=3 THEN '31/03/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=4 THEN '30/04/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=5 THEN '31/05/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=6 THEN '30/06/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=7 THEN '31/07/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=8 THEN '31/08/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=9 THEN '30/09/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=10 THEN '31/10/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=11 THEN '30/11/'||TO_CHAR(SYSDATE,'YYYY') WHEN TO_NUMBER(TO_CHAR(SYSDATE,'MM'))=12 THEN '31/12/'||TO_CHAR(SYSDATE,'YYYY') END
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'D\+[0-9]{1,3}(?![0-9])')
        THEN TO_CHAR(SYSDATE+TO_NUMBER(REGEXP_SUBSTR(UPPER(TAB_PEDIDOS_RESUMO.OBS),'[0-9]{1,3}(?![0-9])')),'DD/MM/YYYY')
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'AGORA|HOJE') THEN TO_CHAR(SYSDATE,'DD/MM/YYYY')
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'AMANHA|AMANH.') THEN TO_CHAR(SYSDATE+1,'DD/MM/YYYY')
        WHEN REGEXP_LIKE(UPPER(TAB_PEDIDOS_RESUMO.OBS),'ONTEM') THEN TO_CHAR(SYSDATE-1,'DD/MM/YYYY')
        WHEN TAB_PEDIDOS_RESUMO.OBS IS NULL OR TRIM(TAB_PEDIDOS_RESUMO.OBS)='' OR UPPER(TRIM(TAB_PEDIDOS_RESUMO.OBS)) IN ('SEM DATA','N/A','NAO INFORMADO')
        THEN TO_CHAR(TAB_PEDIDOS_RESUMO.DT_ENTREGA_CLI,'DD/MM/YYYY')
        ELSE TO_CHAR(TAB_PEDIDOS_RESUMO.DT_ENTREGA_CLI,'DD/MM/YYYY')
    END AS DATA_FORMATADA
    FROM TAB_PEDIDOS_RESUMO
    LEFT JOIN CLIENTES_PROGRAMACAO_V3 ON CLIENTES_PROGRAMACAO_V3.COD_CLI = TAB_PEDIDOS_RESUMO.COD_CLIENTE
) q
ENDSQL;

$pdo = null;
try {
    $pdo = \core\Database::getInstance('focco');
    $pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

    echo "Desabilitando trigger SQLS_TR...\n";
    $pdo->exec("ALTER TRIGGER FOCCO3I.SQLS_TR DISABLE");

    echo "Removendo registro anterior (se existir)...\n";
    $pdo->exec("DELETE FROM FOCCO3I.GAZIN_SQLS WHERE IDSQL = '$idsql'");

    echo "Inserindo com EMPTY_CLOB...\n";
    $pdo->exec("INSERT INTO FOCCO3I.GAZIN_SQLS (IDSQL, SQL) VALUES ('$idsql', EMPTY_CLOB())");

    echo "Escrevendo conteudo em chunks...\n";
    $chunkSize = 2000;
    $chunks    = str_split($sql, $chunkSize);
    $total     = count($chunks);

    foreach ($chunks as $i => $chunk) {
        $escaped = str_replace("'", "''", $chunk);
        if ($i === 0) {
            $pdo->exec("UPDATE FOCCO3I.GAZIN_SQLS SET SQL = TO_CLOB('$escaped') WHERE IDSQL = '$idsql'");
        } else {
            $pdo->exec("UPDATE FOCCO3I.GAZIN_SQLS SET SQL = SQL || TO_CLOB('$escaped') WHERE IDSQL = '$idsql'");
        }
        echo "  chunk " . ($i + 1) . "/$total\n";
    }

    $pdo->exec("COMMIT");

    echo "Reabilitando trigger SQLS_TR...\n";
    $pdo->exec("ALTER TRIGGER FOCCO3I.SQLS_TR ENABLE");

    echo "\nOK: '$idsql' salvo com sucesso!\n";

} catch (\Exception $e) {
    echo "ERRO: " . $e->getMessage() . "\n";
    if ($pdo) { try { $pdo->exec("ALTER TRIGGER FOCCO3I.SQLS_TR ENABLE"); } catch (\Exception $e2) {} }
    exit(1);
}
