-- ============================================
-- 5. TABELA DE VÍNCULO FUNCIONÁRIO/RECURSO/CENTRO
-- Estrutura sem constraints (constraints serão adicionadas via ALTER TABLE)
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_VINC_FUNC (
    ID_VINCULO         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR            NUMBER(10) NOT NULL,
    ID_FUNCIONARIO     NUMBER(10) NOT NULL,
    ID_RECURSO         NUMBER(10),                     -- NULL para funcionários de APOIO
    ID_CENTRO_TRAB     NUMBER(10) NOT NULL,
    TIPO_VINCULO       CHAR(1) DEFAULT 'N' NOT NULL,   -- N=Normal, A=Apoio (ganha sobre total do centro)
    ATIVO              CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CADASTRO        DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD     NUMBER(10)
);

-- Comentário sobre TIPO_VINCULO
COMMENT ON COLUMN FOCCO3I.TGAZIN_VINC_FUNC.TIPO_VINCULO IS 'N=Normal (vinculado ao recurso), A=Apoio (ganha sobre produtividade total do centro)';

CREATE INDEX FOCCO3I.IX_VINC_FUNC ON FOCCO3I.TGAZIN_VINC_FUNC(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_VINC_RECURSO ON FOCCO3I.TGAZIN_VINC_FUNC(ID_RECURSO);
CREATE INDEX FOCCO3I.IX_VINC_CENTRO ON FOCCO3I.TGAZIN_VINC_FUNC(ID_CENTRO_TRAB);
CREATE INDEX FOCCO3I.IX_VINC_EMPR ON FOCCO3I.TGAZIN_VINC_FUNC(ID_EMPR);
CREATE INDEX FOCCO3I.IX_VINC_TIPO ON FOCCO3I.TGAZIN_VINC_FUNC(TIPO_VINCULO);

-- ALTER TABLE para adicionar TIPO_VINCULO se tabela já existir
-- ALTER TABLE FOCCO3I.TGAZIN_VINC_FUNC ADD TIPO_VINCULO CHAR(1) DEFAULT 'N' NOT NULL;
-- ALTER TABLE FOCCO3I.TGAZIN_VINC_FUNC MODIFY ID_RECURSO NUMBER(10) NULL;
-- ============================================
-- Sistema de Comissionamento de Produtividade
-- DDL das Tabelas Customizadas
-- Banco: Oracle (FOCCO)
-- ============================================

-- ============================================
-- 1. TABELA DE PONTUAÇÃO POR PRODUTO (UP)
-- Armazena os pontos por unidade produzida de cada produto
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_PONTUACAO_PRODUTO (
    ID_PONTUACAO        NUMBER(10) NOT NULL,
    ID_EMPR             NUMBER(10) NOT NULL,           -- FK para TEMPRESAS (Empresa)
    ID_ITEM             NUMBER(10) NOT NULL,           -- FK para TITENS
    ID_ITEMPR           NUMBER(10),                    -- FK para TITENS_EMPR (Item por Empresa)
    ID_MASCARA          NUMBER(10),                    -- FK para TMASC_ITEM (Máscara do item)
    ID_CENTRO_TRAB      NUMBER(10),                    -- FK para TCENTROS_TRAB (NULL = todos)
    PONTOS_UP           NUMBER(10,4) NOT NULL,         -- Pontos por UP
    DT_VIGENCIA_INI     DATE NOT NULL,                 -- Data início vigência
    DT_VIGENCIA_FIM     DATE,                          -- Data fim vigência (NULL = sem fim)
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,  -- S=Sim, N=Não
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

-- Sequence para ID automático
CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_PONTUACAO_PROD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Índices para performance
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_EMPR ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(ID_EMPR);
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_ITEM ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(ID_ITEM);
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_ITEMPR ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(ID_ITEMPR);
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_MASCARA ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(ID_MASCARA);
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_CENTRO ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(ID_CENTRO_TRAB);
CREATE INDEX FOCCO3I.IX_GAZIN_PONT_VIGENCIA ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO(DT_VIGENCIA_INI, DT_VIGENCIA_FIM);

-- Comentários
COMMENT ON TABLE FOCCO3I.TGAZIN_PONTUACAO_PRODUTO IS 'Tabela de pontuação UP por produto para sistema de comissão';
COMMENT ON COLUMN FOCCO3I.TGAZIN_PONTUACAO_PRODUTO.ID_EMPR IS 'ID da empresa (filial)';
COMMENT ON COLUMN FOCCO3I.TGAZIN_PONTUACAO_PRODUTO.ID_ITEMPR IS 'ID do item por empresa (TITENS_EMPR)';
COMMENT ON COLUMN FOCCO3I.TGAZIN_PONTUACAO_PRODUTO.ID_MASCARA IS 'ID da máscara do item (variação/configuração)';
COMMENT ON COLUMN FOCCO3I.TGAZIN_PONTUACAO_PRODUTO.PONTOS_UP IS 'Quantidade de pontos ganhos por UP produzida do produto';

-- ============================================
-- ALTER TABLE para adicionar colunas se tabela já existir
-- ============================================
-- ALTER TABLE FOCCO3I.TGAZIN_PONTUACAO_PRODUTO ADD ID_EMPR NUMBER(10);
-- ALTER TABLE FOCCO3I.TGAZIN_PONTUACAO_PRODUTO ADD ID_ITEMPR NUMBER(10);
-- ALTER TABLE FOCCO3I.TGAZIN_PONTUACAO_PRODUTO ADD ID_MASCARA NUMBER(10);

-- ============================================
-- 2. TABELA DE FAIXAS DE COMISSÃO
-- Define as faixas de comissão por percentual ou quantidade
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_FAIXA_COMISSAO (
    ID_FAIXA            NUMBER(10) NOT NULL,
    DESCRICAO           VARCHAR2(100) NOT NULL,        -- Descrição da faixa
    TIPO                CHAR(1) NOT NULL,              -- P=Percentual, Q=Quantidade
    PONTO_INICIAL       NUMBER(10,2) NOT NULL,         -- Pontuação mínima da faixa
    PONTO_FINAL         NUMBER(10,2),                  -- Pontuação máxima (NULL = sem limite)
    VALOR_COMISSAO      NUMBER(10,2) NOT NULL,         -- Valor ou percentual da comissão
    ID_CENTRO_TRAB      NUMBER(10),                    -- FK para TCENTROS_TRAB (NULL = todos)
    DT_VIGENCIA_INI     DATE NOT NULL,                 -- Data início vigência
    DT_VIGENCIA_FIM     DATE,                          -- Data fim vigência
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

-- Sequence para ID automático
CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_FAIXA_COMISSAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Índices para performance
CREATE INDEX FOCCO3I.IX_GAZIN_FAIXA_CENTRO ON FOCCO3I.TGAZIN_FAIXA_COMISSAO(ID_CENTRO_TRAB);
CREATE INDEX FOCCO3I.IX_GAZIN_FAIXA_PONTOS ON FOCCO3I.TGAZIN_FAIXA_COMISSAO(PONTO_INICIAL, PONTO_FINAL);
CREATE INDEX FOCCO3I.IX_GAZIN_FAIXA_VIGENCIA ON FOCCO3I.TGAZIN_FAIXA_COMISSAO(DT_VIGENCIA_INI, DT_VIGENCIA_FIM);

-- Comentários
COMMENT ON TABLE FOCCO3I.TGAZIN_FAIXA_COMISSAO IS 'Tabela de faixas de comissão para sistema de produtividade';
COMMENT ON COLUMN FOCCO3I.TGAZIN_FAIXA_COMISSAO.TIPO IS 'P=Comissão como percentual sobre pontos, Q=Valor fixo por faixa';
COMMENT ON COLUMN FOCCO3I.TGAZIN_FAIXA_COMISSAO.VALOR_COMISSAO IS 'Se TIPO=P: percentual (ex: 5.00 = 5%), Se TIPO=Q: valor em R$';

-- ============================================
-- 3. TABELA DE COMISSÕES CALCULADAS
-- Armazena o histórico de comissões calculadas por funcionário
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_COMISSAO_CALC (
    ID_COMISSAO         NUMBER(10) NOT NULL,
    ID_FUNCIONARIO      NUMBER(10) NOT NULL,           -- FK para TFUNCIONARIOS
    ID_FAIXA            NUMBER(10),                    -- FK para TGAZIN_FAIXA_COMISSAO
    DT_INICIO           DATE NOT NULL,                 -- Período início
    DT_FIM              DATE NOT NULL,                 -- Período fim
    TOTAL_PONTOS        NUMBER(12,2) NOT NULL,         -- Total de pontos no período
    VALOR_COMISSAO      NUMBER(12,2) NOT NULL,         -- Valor calculado da comissão
    STATUS              CHAR(1) DEFAULT 'P' NOT NULL,  -- P=Pendente, A=Aprovado, C=Cancelado
    DT_PROCESSAMENTO    DATE DEFAULT SYSDATE NOT NULL, -- Data do cálculo
    ID_USUARIO_PROC     NUMBER(10),                    -- Usuário que processou
    DT_APROVACAO        DATE,                          -- Data da aprovação
    ID_USUARIO_APROV    NUMBER(10),                    -- Usuário que aprovou
    OBSERVACAO          VARCHAR2(500)                  -- Observações
);

-- Sequence para ID automático
CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_COMISSAO_CALC
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Índices para performance
CREATE INDEX FOCCO3I.IX_GAZIN_COMISSAO_FUNC ON FOCCO3I.TGAZIN_COMISSAO_CALC(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_GAZIN_COMISSAO_PERIODO ON FOCCO3I.TGAZIN_COMISSAO_CALC(DT_INICIO, DT_FIM);
CREATE INDEX FOCCO3I.IX_GAZIN_COMISSAO_STATUS ON FOCCO3I.TGAZIN_COMISSAO_CALC(STATUS);
CREATE INDEX FOCCO3I.IX_GAZIN_COMISSAO_DT_PROC ON FOCCO3I.TGAZIN_COMISSAO_CALC(DT_PROCESSAMENTO);

-- Comentários
COMMENT ON TABLE FOCCO3I.TGAZIN_COMISSAO_CALC IS 'Histórico de comissões calculadas por funcionário';
COMMENT ON COLUMN FOCCO3I.TGAZIN_COMISSAO_CALC.STATUS IS 'P=Pendente aprovação, A=Aprovado para pagamento, C=Cancelado';

-- ============================================
-- 4. TABELA DE LOG DE APONTAMENTOS PROCESSADOS
-- (Opcional) Para rastrear quais apontamentos foram considerados
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_COMISSAO_APONTAMENTO (
    ID_COMISSAO_APT     NUMBER(10) NOT NULL,
    ID_COMISSAO         NUMBER(10) NOT NULL,           -- FK para TGAZIN_COMISSAO_CALC
    ID_APONTAMENTO      NUMBER(10) NOT NULL,           -- FK para TAPONTAMENTOS_PROD
    PONTOS_CALCULADOS   NUMBER(10,4) NOT NULL          -- Pontos deste apontamento
);

-- Sequence para ID automático
CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_COMISSAO_APT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Índices
CREATE INDEX FOCCO3I.IX_GAZIN_COMAPT_COMISSAO ON FOCCO3I.TGAZIN_COMISSAO_APONTAMENTO(ID_COMISSAO);
CREATE INDEX FOCCO3I.IX_GAZIN_COMAPT_APT ON FOCCO3I.TGAZIN_COMISSAO_APONTAMENTO(ID_APONTAMENTO);

-- ============================================
-- GRANTS (ajuste conforme necessário)
-- ============================================
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO TO PUBLIC;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FOCCO3I.TGAZIN_FAIXA_COMISSAO TO PUBLIC;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FOCCO3I.TGAZIN_COMISSAO_CALC TO PUBLIC;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FOCCO3I.TGAZIN_COMISSAO_APONTAMENTO TO PUBLIC;
-- GRANT SELECT ON FOCCO3I.SEQ_GAZIN_PONTUACAO_PROD TO PUBLIC;
-- GRANT SELECT ON FOCCO3I.SEQ_GAZIN_FAIXA_COMISSAO TO PUBLIC;
-- GRANT SELECT ON FOCCO3I.SEQ_GAZIN_COMISSAO_CALC TO PUBLIC;
-- GRANT SELECT ON FOCCO3I.SEQ_GAZIN_COMISSAO_APT TO PUBLIC;

-- ============================================
-- 6. TABELA DE FALTAS DE FUNCIONÁRIOS
-- Registra faltas para bloqueio de comissão diária
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_FALTA_FUNC (
    ID_FALTA            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR             NUMBER(10) NOT NULL,           -- FK para TEMPRESAS
    ID_FUNCIONARIO      NUMBER(10) NOT NULL,           -- FK para TFUNCIONARIOS
    DT_FALTA            DATE NOT NULL,                 -- Data da falta
    MOTIVO              VARCHAR2(500),                 -- Motivo da falta
    TIPO_FALTA          CHAR(1) DEFAULT 'I' NOT NULL, -- I=Integral, P=Parcial
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,  -- S=Sim, N=Não (excluído lógico)
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_FALTA_FUNC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX FOCCO3I.IX_FALTA_FUNC ON FOCCO3I.TGAZIN_FALTA_FUNC(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_FALTA_DATA ON FOCCO3I.TGAZIN_FALTA_FUNC(DT_FALTA);
CREATE INDEX FOCCO3I.IX_FALTA_EMPR ON FOCCO3I.TGAZIN_FALTA_FUNC(ID_EMPR);
CREATE UNIQUE INDEX FOCCO3I.IX_FALTA_UNICA ON FOCCO3I.TGAZIN_FALTA_FUNC(ID_FUNCIONARIO, DT_FALTA, ATIVO);

COMMENT ON TABLE FOCCO3I.TGAZIN_FALTA_FUNC IS 'Registros de faltas de funcionários para bloqueio de comissão';
COMMENT ON COLUMN FOCCO3I.TGAZIN_FALTA_FUNC.TIPO_FALTA IS 'I=Falta Integral (comissão zerada), P=Parcial';

-- ============================================
-- 7. TABELA DE RETRABALHO
-- Registra retrabalhos com impacto na comissão
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_RETRABALHO (
    ID_RETRABALHO       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR             NUMBER(10) NOT NULL,           -- FK para TEMPRESAS
    ID_FUNCIONARIO      NUMBER(10) NOT NULL,           -- FK para TFUNCIONARIOS
    ID_RECURSO          NUMBER(10),                    -- FK para TMAQUINAS
    ID_ITEM             NUMBER(10) NOT NULL,           -- FK para TITENS
    ID_MASCARA          NUMBER(10),                    -- FK para TMASC_ITEM
    ID_ORDEM            NUMBER(10),                    -- FK para TORDENS (opcional)
    DT_RETRABALHO       DATE NOT NULL,                 -- Data do retrabalho
    QUANTIDADE          NUMBER(10,2) NOT NULL,         -- Quantidade retrabalhada
    MOTIVO              VARCHAR2(500),                 -- Motivo do retrabalho
    TIPO_IMPACTO        CHAR(1) DEFAULT 'P' NOT NULL,  -- P=Percentual, V=Valor fixo, Z=Zerar
    VALOR_IMPACTO       NUMBER(10,4) DEFAULT 0,        -- Percentual de penalização ou valor
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_RETRABALHO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX FOCCO3I.IX_RETRAB_FUNC ON FOCCO3I.TGAZIN_RETRABALHO(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_RETRAB_DATA ON FOCCO3I.TGAZIN_RETRABALHO(DT_RETRABALHO);
CREATE INDEX FOCCO3I.IX_RETRAB_ITEM ON FOCCO3I.TGAZIN_RETRABALHO(ID_ITEM);
CREATE INDEX FOCCO3I.IX_RETRAB_EMPR ON FOCCO3I.TGAZIN_RETRABALHO(ID_EMPR);

COMMENT ON TABLE FOCCO3I.TGAZIN_RETRABALHO IS 'Registros de retrabalho com impacto na comissão';
COMMENT ON COLUMN FOCCO3I.TGAZIN_RETRABALHO.TIPO_IMPACTO IS 'P=Percentual de redução, V=Valor fixo de desconto, Z=Zerar comissão do item';

-- ============================================
-- 8. TABELA DE VÍNCULO DE APONTAMENTOS SEM RECURSO
-- Permite vincular apontamentos que não possuem RECURSO_ID a um funcionário
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_VINC_APONTAMENTO (
    ID_VINC_APT         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR             NUMBER(10) NOT NULL,           -- FK para TEMPRESAS
    ID_APONTAMENTO      NUMBER(10) NOT NULL,           -- FK para TAPONTAMENTOS_PROD / TORDENS_MOVTO
    ID_FUNCIONARIO      NUMBER(10) NOT NULL,           -- FK para TFUNCIONARIOS
    ID_RECURSO          NUMBER(10),                    -- FK para TMAQUINAS (opcional)
    FECHADO             CHAR(1) DEFAULT 'N' NOT NULL,  -- N=Aberto, S=Fechado (não editável)
    DT_VINCULACAO       DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_VINC     NUMBER(10),                    -- Usuário que fez a vinculação
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10),
    OBSERVACAO          VARCHAR2(500)
);

CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_VINC_APT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX FOCCO3I.IX_VINCAPT_APT ON FOCCO3I.TGAZIN_VINC_APONTAMENTO(ID_APONTAMENTO);
CREATE INDEX FOCCO3I.IX_VINCAPT_FUNC ON FOCCO3I.TGAZIN_VINC_APONTAMENTO(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_VINCAPT_EMPR ON FOCCO3I.TGAZIN_VINC_APONTAMENTO(ID_EMPR);
CREATE UNIQUE INDEX FOCCO3I.IX_VINCAPT_UNICO ON FOCCO3I.TGAZIN_VINC_APONTAMENTO(ID_APONTAMENTO);

COMMENT ON TABLE FOCCO3I.TGAZIN_VINC_APONTAMENTO IS 'Vinculação manual de apontamentos sem recurso a funcionários';
COMMENT ON COLUMN FOCCO3I.TGAZIN_VINC_APONTAMENTO.FECHADO IS 'N=Permite edição, S=Não permite alteração';

-- ============================================
-- 9. TABELA DE REGRAS ESPECÍFICAS POR FUNCIONÁRIO
-- Define regras de comissão específicas por funcionário
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_REGRA_FUNC (
    ID_REGRA            NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR             NUMBER(10) NOT NULL,           -- FK para TEMPRESAS
    ID_FUNCIONARIO      NUMBER(10) NOT NULL,           -- FK para TFUNCIONARIOS
    ID_CENTRO_TRAB      NUMBER(10),                    -- FK para TCENTROS_TRAB (opcional)
    DESCRICAO           VARCHAR2(200),                 -- Descrição da regra
    TIPO_COMISSAO       CHAR(1) NOT NULL,              -- P=Percentual, V=Valor fixo por UP, F=Valor fixo total
    VALOR_COMISSAO      NUMBER(10,4) NOT NULL,         -- Valor ou percentual
    DT_VIGENCIA_INI     DATE NOT NULL,                 -- Início da vigência
    DT_VIGENCIA_FIM     DATE,                          -- Fim da vigência (NULL = sem fim)
    PRIORIDADE          NUMBER(3) DEFAULT 1,           -- Prioridade (maior = mais importante)
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_REGRA_FUNC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX FOCCO3I.IX_REGRA_FUNC ON FOCCO3I.TGAZIN_REGRA_FUNC(ID_FUNCIONARIO);
CREATE INDEX FOCCO3I.IX_REGRA_VIGENCIA ON FOCCO3I.TGAZIN_REGRA_FUNC(DT_VIGENCIA_INI, DT_VIGENCIA_FIM);
CREATE INDEX FOCCO3I.IX_REGRA_EMPR ON FOCCO3I.TGAZIN_REGRA_FUNC(ID_EMPR);
CREATE INDEX FOCCO3I.IX_REGRA_CENTRO ON FOCCO3I.TGAZIN_REGRA_FUNC(ID_CENTRO_TRAB);

COMMENT ON TABLE FOCCO3I.TGAZIN_REGRA_FUNC IS 'Regras específicas de comissão por funcionário';
COMMENT ON COLUMN FOCCO3I.TGAZIN_REGRA_FUNC.TIPO_COMISSAO IS 'P=Percentual sobre pontos, V=Valor por UP, F=Valor fixo total';
COMMENT ON COLUMN FOCCO3I.TGAZIN_REGRA_FUNC.PRIORIDADE IS 'Quanto maior, mais prioritária a regra';

-- ============================================
-- 10. TABELA DE LOG DE AUDITORIA
-- Registra todas as operações críticas do sistema
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_LOG_AUDITORIA (
    ID_LOG              NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EMPR             NUMBER(10),                    -- FK para TEMPRESAS
    TABELA              VARCHAR2(100) NOT NULL,        -- Nome da tabela afetada
    ID_REGISTRO         NUMBER(10),                    -- ID do registro afetado
    OPERACAO            CHAR(1) NOT NULL,              -- I=Insert, U=Update, D=Delete
    DADOS_ANTERIORES    CLOB,                          -- JSON com dados antes da alteração
    DADOS_NOVOS         CLOB,                          -- JSON com dados após alteração
    DT_OPERACAO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO          NUMBER(10),
    IP_USUARIO          VARCHAR2(50),
    OBSERVACAO          VARCHAR2(500)
);

CREATE SEQUENCE FOCCO3I.SEQ_GAZIN_LOG_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX FOCCO3I.IX_LOG_TABELA ON FOCCO3I.TGAZIN_LOG_AUDITORIA(TABELA);
CREATE INDEX FOCCO3I.IX_LOG_REGISTRO ON FOCCO3I.TGAZIN_LOG_AUDITORIA(ID_REGISTRO);
CREATE INDEX FOCCO3I.IX_LOG_DATA ON FOCCO3I.TGAZIN_LOG_AUDITORIA(DT_OPERACAO);
CREATE INDEX FOCCO3I.IX_LOG_USUARIO ON FOCCO3I.TGAZIN_LOG_AUDITORIA(ID_USUARIO);

COMMENT ON TABLE FOCCO3I.TGAZIN_LOG_AUDITORIA IS 'Log de auditoria de todas as operações críticas';
COMMENT ON COLUMN FOCCO3I.TGAZIN_LOG_AUDITORIA.OPERACAO IS 'I=Insert, U=Update, D=Delete';

-- ============================================
-- 11. MODIFICAR TABELA DE COMISSÃO CALCULADA
-- Adicionar campos para rastreabilidade
-- ============================================
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD TOTAL_FALTAS NUMBER(5) DEFAULT 0;
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD TOTAL_RETRABALHO NUMBER(12,2) DEFAULT 0;
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD VALOR_RETRABALHO NUMBER(12,2) DEFAULT 0;
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD USA_REGRA_ESPECIFICA CHAR(1) DEFAULT 'N';
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD ID_REGRA_FUNC NUMBER(10);
-- ALTER TABLE FOCCO3I.TGAZIN_COMISSAO_CALC ADD BLOQUEADO_FALTA CHAR(1) DEFAULT 'N';

-- ============================================
-- 12. TABELA DE PERMISSÕES DE ACESSO DO USUÁRIO
-- Define quais módulos cada usuário pode acessar
-- ============================================
CREATE TABLE FOCCO3I.TGAZIN_ACESSO_USUARIO (
    ID_ACESSO           NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LOGIN_USUARIO       VARCHAR2(100) NOT NULL,         -- Login do usuário (mesmo usado na autenticação FOCCO)
    ACESSO_CD           CHAR(1) DEFAULT 'N' NOT NULL,   -- S=Sim, N=Não (acesso ao módulo CD)
    ACESSO_COMISSAO     CHAR(1) DEFAULT 'N' NOT NULL,   -- S=Sim, N=Não (acesso ao módulo Comissão)
    ADMIN               CHAR(1) DEFAULT 'N' NOT NULL,   -- S=Sim, N=Não (administrador - pode cadastrar permissões)
    ATIVO               CHAR(1) DEFAULT 'S' NOT NULL,
    DT_CADASTRO         DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO_CAD      NUMBER(10),
    DT_ALTERACAO        DATE,
    ID_USUARIO_ALT      NUMBER(10)
);

CREATE UNIQUE INDEX FOCCO3I.IX_ACESSO_LOGIN ON FOCCO3I.TGAZIN_ACESSO_USUARIO(LOGIN_USUARIO);
CREATE INDEX FOCCO3I.IX_ACESSO_CD ON FOCCO3I.TGAZIN_ACESSO_USUARIO(ACESSO_CD);
CREATE INDEX FOCCO3I.IX_ACESSO_COMISSAO ON FOCCO3I.TGAZIN_ACESSO_USUARIO(ACESSO_COMISSAO);

COMMENT ON TABLE FOCCO3I.TGAZIN_ACESSO_USUARIO IS 'Permissões de acesso aos módulos do sistema por usuário';
COMMENT ON COLUMN FOCCO3I.TGAZIN_ACESSO_USUARIO.LOGIN_USUARIO IS 'Login do usuário FOCCO (uppercase)';
COMMENT ON COLUMN FOCCO3I.TGAZIN_ACESSO_USUARIO.ACESSO_CD IS 'S=Acesso liberado ao módulo CD, N=Sem acesso';
COMMENT ON COLUMN FOCCO3I.TGAZIN_ACESSO_USUARIO.ACESSO_COMISSAO IS 'S=Acesso liberado ao módulo Comissão, N=Sem acesso';
COMMENT ON COLUMN FOCCO3I.TGAZIN_ACESSO_USUARIO.ADMIN IS 'S=Administrador (pode gerenciar permissões), N=Usuário comum';
