-- =============================================================================
-- ÍNDICES DE PERFORMANCE PARA O SISTEMA DE COMISSÕES
-- Execute este script no Oracle para melhorar significativamente a performance
-- =============================================================================

-- IMPORTANTE: Executar com usuário com permissão de CREATE INDEX no schema FOCCO3I

-- =============================================================================
-- 1. ÍNDICES NA TABELA TORDENS_MOVTO (tabela mais acessada)
-- =============================================================================

-- Índice para filtro por data de apontamento (principal filtro das queries)
CREATE INDEX FOCCO3I.IDX_TORDENS_MOVTO_DT_APONT ON FOCCO3I.TORDENS_MOVTO (DT_APONT)
TABLESPACE &TABLESPACE_INDICES;

-- Índice composto para joins frequentes
CREATE INDEX FOCCO3I.IDX_TORDENS_MOVTO_ROTID_DT ON FOCCO3I.TORDENS_MOVTO (TORDEN_ROT_ID, DT_APONT)
TABLESPACE &TABLESPACE_INDICES;


-- =============================================================================
-- 2. ÍNDICES NA TABELA TORDENS_ROT
-- =============================================================================

-- Índice para filtros de apontamento obrigatório
CREATE INDEX FOCCO3I.IDX_TORDENS_ROT_APONTOBR ON FOCCO3I.TORDENS_ROT (APONTAMENTO, OBRIGATORIO, ORDEM_ID)
TABLESPACE &TABLESPACE_INDICES;

-- Índice para join com centro de trabalho
CREATE INDEX FOCCO3I.IDX_TORDENS_ROT_CENTRO ON FOCCO3I.TORDENS_ROT (CENTR_TRAB_ID)
TABLESPACE &TABLESPACE_INDICES;


-- =============================================================================
-- 3. ÍNDICES NA TABELA TORDENS
-- =============================================================================

-- Índice para filtro por empresa
CREATE INDEX FOCCO3I.IDX_TORDENS_EMPRID ON FOCCO3I.TORDENS (EMPR_ID)
TABLESPACE &TABLESPACE_INDICES;


-- =============================================================================
-- 4. ÍNDICES NAS TABELAS CUSTOMIZADAS (TGAZIN_*)
-- =============================================================================

-- TGAZIN_VINC_FUNC (vínculos funcionário-máquina)
CREATE INDEX FOCCO3I.IDX_VINC_FUNC_RECURSO ON FOCCO3I.TGAZIN_VINC_FUNC (ID_RECURSO, ID_CENTRO_TRAB, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_VINC_FUNC_FUNC ON FOCCO3I.TGAZIN_VINC_FUNC (ID_FUNCIONARIO, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_VINC_FUNC_EMPR ON FOCCO3I.TGAZIN_VINC_FUNC (ID_EMPR, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_PONTUACAO_PRODUTO (pontuação de produtos)
CREATE INDEX FOCCO3I.IDX_PONT_PROD_ITEM ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO (ITEM_ID, ATIVO, DT_VIGENCIA_INI)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_PONT_PROD_ITEMPR ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO (ID_ITEMPR, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_PONT_PROD_MASCARA ON FOCCO3I.TGAZIN_PONTUACAO_PRODUTO (ID_MASCARA, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_FALTA_FUNC (faltas)
CREATE INDEX FOCCO3I.IDX_FALTA_FUNC_PERIODO ON FOCCO3I.TGAZIN_FALTA_FUNC (ID_FUNCIONARIO, DT_FALTA, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_FALTA_FUNC_EMPR ON FOCCO3I.TGAZIN_FALTA_FUNC (ID_EMPR, DT_FALTA, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_REGRA_FUNC (regras específicas)
CREATE INDEX FOCCO3I.IDX_REGRA_FUNC_BUSCA ON FOCCO3I.TGAZIN_REGRA_FUNC (ID_FUNCIONARIO, ATIVO, DT_VIGENCIA_INI)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_FAIXA_COMISSAO (faixas de comissão)
CREATE INDEX FOCCO3I.IDX_FAIXA_COMISSAO_BUSCA ON FOCCO3I.TGAZIN_FAIXA_COMISSAO (ATIVO, DT_VIGENCIA_INI, CENTRO_TRAB_ID)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_RETRABALHO (retrabalhos)
CREATE INDEX FOCCO3I.IDX_RETRABALHO_FUNC ON FOCCO3I.TGAZIN_RETRABALHO (ID_FUNCIONARIO, DT_RETRABALHO, ATIVO)
TABLESPACE &TABLESPACE_INDICES;

-- TGAZIN_COMISSAO_CALC (cálculos salvos)
CREATE INDEX FOCCO3I.IDX_COMISSAO_CALC_FUNC ON FOCCO3I.TGAZIN_COMISSAO_CALC (FUNCIONARIO_ID, DT_INICIO, DT_FIM)
TABLESPACE &TABLESPACE_INDICES;

CREATE INDEX FOCCO3I.IDX_COMISSAO_CALC_STATUS ON FOCCO3I.TGAZIN_COMISSAO_CALC (STATUS, DT_INICIO, DT_FIM)
TABLESPACE &TABLESPACE_INDICES;


-- =============================================================================
-- 5. ATUALIZAÇÃO DE ESTATÍSTICAS
-- =============================================================================

-- Após criar os índices, atualize as estatísticas do otimizador
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TORDENS_MOVTO');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TORDENS_ROT');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TORDENS');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_VINC_FUNC');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_PONTUACAO_PRODUTO');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_FALTA_FUNC');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_REGRA_FUNC');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_FAIXA_COMISSAO');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_RETRABALHO');
    DBMS_STATS.GATHER_TABLE_STATS('FOCCO3I', 'TGAZIN_COMISSAO_CALC');
END;
/


-- =============================================================================
-- 6. VIEW MATERIALIZADA PARA RESUMO DIÁRIO (opcional - refresh manual)
-- =============================================================================

-- Esta view materializada pode acelerar muito consultas de resumo
-- Faça REFRESH quando necessário (ex: a cada hora ou manualmente)

CREATE MATERIALIZED VIEW FOCCO3I.MV_APONTAMENTOS_DIARIOS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
ENABLE QUERY REWRITE
AS
SELECT 
    TRUNC(TORDENS_MOVTO.DT_APONT) AS DATA_APONTAMENTO,
    TORDENS.EMPR_ID,
    TORDENS_ROT.CENTR_TRAB_ID,
    VF.ID_FUNCIONARIO,
    COUNT(*) AS QTD_APONTAMENTOS,
    SUM(TORDENS_MOVTO.QUANTIDADE) AS TOTAL_QUANTIDADE
FROM FOCCO3I.TORDENS TORDENS
INNER JOIN FOCCO3I.TORDENS_ROT TORDENS_ROT ON TORDENS.ID = TORDENS_ROT.ORDEM_ID
INNER JOIN FOCCO3I.TORDENS_MOVTO TORDENS_MOVTO ON TORDENS_ROT.ID = TORDENS_MOVTO.TORDEN_ROT_ID
LEFT JOIN FOCCO3I.TORD_MOV_FAB_MAQ TORD_MOV_FAB_MAQ ON TORDENS_MOVTO.ID = TORD_MOV_FAB_MAQ.ORDEM_MOVT_ID
LEFT JOIN FOCCO3I.TMAQUINAS TMAQUINAS ON TMAQUINAS.ID = TORD_MOV_FAB_MAQ.MAQUINA_ID
LEFT JOIN FOCCO3I.TGAZIN_VINC_FUNC VF ON VF.ID_RECURSO = TMAQUINAS.ID
    AND VF.ID_CENTRO_TRAB = TORDENS_ROT.CENTR_TRAB_ID
    AND VF.ATIVO = 'S'
    AND VF.ID_EMPR = TORDENS.EMPR_ID
WHERE TORDENS_ROT.APONTAMENTO = 1
AND TORDENS_ROT.OBRIGATORIO = 1
AND TORDENS_MOVTO.DT_APONT >= ADD_MONTHS(SYSDATE, -3) -- últimos 3 meses
GROUP BY 
    TRUNC(TORDENS_MOVTO.DT_APONT),
    TORDENS.EMPR_ID,
    TORDENS_ROT.CENTR_TRAB_ID,
    VF.ID_FUNCIONARIO;

-- Índice na view materializada
CREATE INDEX FOCCO3I.IDX_MV_APON_DIA_FUNC ON FOCCO3I.MV_APONTAMENTOS_DIARIOS 
    (DATA_APONTAMENTO, ID_FUNCIONARIO, EMPR_ID);


-- =============================================================================
-- COMANDO PARA REFRESH DA VIEW MATERIALIZADA
-- =============================================================================
-- Execute periodicamente (ex: via job ou manualmente):
-- BEGIN
--     DBMS_MVIEW.REFRESH('FOCCO3I.MV_APONTAMENTOS_DIARIOS', 'C');
-- END;
-- /
